export enum FolderValidationErrorType {
    FOLDER_NAME_EMPTY = "FOLDER_NAME_EMPTY",
    FOLDER_NAME_TOO_LONG = "FOLDER_NAME_TOO_LONG",
    FOLDER_ALREADY_EXISTS = "FOLDER_ALREADY_EXISTS",
}

export enum FileValidationErrorType {
    FILE_NAME_EMPTY = "FILE_NAME_EMPTY",
    FILE_NAME_TOO_LONG = "FILE_NAME_TOO_LONG",
    FILE_CONTENT_TYPE_EMPTY = "FILE_CONTENT_TYPE_EMPTY",
    FILE_VERSION_NEGATIVE = "FILE_VERSION_NEGATIVE",
    FILE_SIZE_NEGATIVE = "FILE_SIZE_NEGATIVE",
    FILE_ALREADY_EXISTS = "FILE_ALREADY_EXISTS",
}

export type ValidationErrorType =
    FolderValidationErrorType
    | FileValidationErrorType;