services:
  backend:
    container_name: backend
    image: registry.gitlab.com/realflorianchrist/infboard/backend-dev:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    depends_on:
      - mongo
      - minio

  frontend:
    container_name: frontend
    image: registry.gitlab.com/realflorianchrist/infboard/frontend-dev:latest
    restart: always
    ports:
      - "80:3000"

  minio:
    image: quay.io/minio/minio
    restart: always
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web UI
    command: server /data --console-address ":9001"
    env_file:
      - backend/s3/.env
    volumes:
      - minio-data:/data

  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - backend/db/.env
    command: [ "--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile", "--bind_ip_all" ]
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-keyfile:/etc/mongo-keyfile:ro

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - backend/db/.env
    depends_on:
      - mongo

volumes:
  minio-data:
  mongo_data:
  mongo_config: