services:
  backend:
    image: registry.gitlab.com/realflorianchrist/infboard/backend-dev:latest
    ports:
      - "8080:8080"
    environment:
      # Environment
      NODE_ENV: production

      # Server
      PORT: 8080
      HOST: 89.119.48.9

      # Frontend
      FRONTEND_URL: http://89.119.48.9:80

      # Jet Logger
      JET_LOGGER_MODE: CONSOLE
      JET_LOGGER_FILEPATH: jet-logger.log
      JET_LOGGER_TIMESTAMP: "TRUE"
      JET_LOGGER_FORMAT: LINE

      # MongoDB
      MONGO_HOST: localhost:27017
      MONGO_DATABASE: infboard_db
      MONGO_USER: infboardUser
      MONGO_PASSWORD: password

      # S3 / MinIO
      S3_REGION: us-east-1
      S3_ENDPOINT: http://localhost:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET: infboard-bucket
      S3_UPLOAD_FOLDER: upload
      S3_EXPIRE_URL_SECONDS: 60

  frontend:
    image: registry.gitlab.com/realflorianchrist/infboard/frontend-dev:latest
    ports:
      - "80:3000"

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web UI
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data

  mongodb:
    image: mongo
    container_name: mongodb_lokal
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: infboard_db
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/

volumes:
  minio-data:
  mongo_data:
  mongo_config:
