import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "@workspace/ui/globals.css"
import Header from "../components/header/Header";
import Providers from "@/src/providers/Providers";
import {Toaster} from "@workspace/ui/components/sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Infboard",
    description: "Generated by create next app",
};

export default function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <html lang="de">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Providers>
            <Header/>
            <main>
                {children}
            </main>
            <Toaster position={'bottom-right'} richColors/>
        </Providers>
        </body>
        </html>
    );
}
