services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  mongodb:
    image: mongo
    container_name: mongodb_lokal
    hostname: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

      MONGO_REPLICA_SET_NAME: rs0
      MONGO_REPLICA_HOST: mongodb:27017

      MONGO_APP_DATABASE: infboard_db
      MONGO_APP_USERNAME: infboardUser
      MONGO_APP_PASSWORD: password
    command: [ "--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile", "--bind_ip_all" ]
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./init-replica.js:/scripts/init-replica.js:ro
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --port 27017 -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin /scripts/init-replica.js --quiet" ]
      interval: 5s
      timeout: 30s
      retries: 30

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/admin?replicaSet=rs0&authSource=admin
    depends_on:
      - mongodb

volumes:
  minio-data:
  mongo_data:
  mongo_config:
