export enum FolderValidationErrorType {
    FOLDER_NAME_EMPTY = "FOLDER_NAME_EMPTY",
    FOLDER_NAME_TOO_LONG = "FOLDER_NAME_TOO_LONG",
    FOLDER_ALREADY_EXISTS = "FOLDER_ALREADY_EXISTS",
    FOLDER_EXISTS_DELETED = "FOLDER_EXISTS_DELETED",
    CANNOT_MOVE_INTO_SELF_OR_DESCENDANT = "CANNOT_MOVE_INTO_SELF_OR_DESCENDANT",
    FOLDER_VERSION_NEGATIVE = "FOLDER_VERSION_NEGATIVE",
}

export enum FileValidationErrorType {
    FILE_NAME_EMPTY = "FILE_NAME_EMPTY",
    FILE_NAME_TOO_LONG = "FILE_NAME_TOO_LONG",
    FILE_CONTENT_TYPE_EMPTY = "FILE_CONTENT_TYPE_EMPTY",
    FILE_VERSION_NEGATIVE = "FILE_VERSION_NEGATIVE",
    FILE_SIZE_NEGATIVE = "FILE_SIZE_NEGATIVE",
    FILE_ALREADY_EXISTS = "FILE_ALREADY_EXISTS",
}

export enum UserValidationErrorType {
    USERNAME_TOO_SHORT = "USERNAME_TOO_SHORT",
    USERNAME_TOO_LONG = "USERNAME_TOO_LONG",
    INVALID_EMAIL = "INVALID_EMAIL",
    NOT_AN_FHNW_EMAIL = "NOT_AN_FHNW_EMAIL",
    PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT",
    PASSWORD_TOO_LONG = "PASSWORD_TOO_LONG",
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS",
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
    PASSWORDS_NOT_MATCHING = "PASSWORDS_NOT_MATCHING",
}

export type ValidationErrorType =
    FolderValidationErrorType
    | FileValidationErrorType
    | UserValidationErrorType;